// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: market/v1/market.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockBasic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsCode        string                 `protobuf:"bytes,1,opt,name=ts_code,json=tsCode,proto3" json:"ts_code,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Market        string                 `protobuf:"bytes,4,opt,name=market,proto3" json:"market,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockBasic) Reset() {
	*x = StockBasic{}
	mi := &file_market_v1_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockBasic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockBasic) ProtoMessage() {}

func (x *StockBasic) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockBasic.ProtoReflect.Descriptor instead.
func (*StockBasic) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{0}
}

func (x *StockBasic) GetTsCode() string {
	if x != nil {
		return x.TsCode
	}
	return ""
}

func (x *StockBasic) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StockBasic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StockBasic) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

type SearchStocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStocksRequest) Reset() {
	*x = SearchStocksRequest{}
	mi := &file_market_v1_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStocksRequest) ProtoMessage() {}

func (x *SearchStocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStocksRequest.ProtoReflect.Descriptor instead.
func (*SearchStocksRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{1}
}

func (x *SearchStocksRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchStocksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchStocksReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stocks        []*StockBasic          `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStocksReply) Reset() {
	*x = SearchStocksReply{}
	mi := &file_market_v1_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStocksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStocksReply) ProtoMessage() {}

func (x *SearchStocksReply) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStocksReply.ProtoReflect.Descriptor instead.
func (*SearchStocksReply) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{2}
}

func (x *SearchStocksReply) GetStocks() []*StockBasic {
	if x != nil {
		return x.Stocks
	}
	return nil
}

type GetRealtimeQuotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codes         []string               `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealtimeQuotesRequest) Reset() {
	*x = GetRealtimeQuotesRequest{}
	mi := &file_market_v1_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealtimeQuotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealtimeQuotesRequest) ProtoMessage() {}

func (x *GetRealtimeQuotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealtimeQuotesRequest.ProtoReflect.Descriptor instead.
func (*GetRealtimeQuotesRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{3}
}

func (x *GetRealtimeQuotesRequest) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

type Quote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Open          string                 `protobuf:"bytes,4,opt,name=open,proto3" json:"open,omitempty"`
	PreClose      string                 `protobuf:"bytes,5,opt,name=pre_close,json=preClose,proto3" json:"pre_close,omitempty"`
	High          string                 `protobuf:"bytes,6,opt,name=high,proto3" json:"high,omitempty"`
	Low           string                 `protobuf:"bytes,7,opt,name=low,proto3" json:"low,omitempty"`
	ChangePercent float64                `protobuf:"fixed64,8,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	ChangePrice   float64                `protobuf:"fixed64,9,opt,name=change_price,json=changePrice,proto3" json:"change_price,omitempty"`
	Date          string                 `protobuf:"bytes,10,opt,name=date,proto3" json:"date,omitempty"`
	Time          string                 `protobuf:"bytes,11,opt,name=time,proto3" json:"time,omitempty"`
	Volume        string                 `protobuf:"bytes,12,opt,name=volume,proto3" json:"volume,omitempty"`
	Amount        string                 `protobuf:"bytes,13,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_market_v1_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{4}
}

func (x *Quote) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Quote) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Quote) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Quote) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *Quote) GetPreClose() string {
	if x != nil {
		return x.PreClose
	}
	return ""
}

func (x *Quote) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *Quote) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *Quote) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *Quote) GetChangePrice() float64 {
	if x != nil {
		return x.ChangePrice
	}
	return 0
}

func (x *Quote) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Quote) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Quote) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *Quote) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type GetRealtimeQuotesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quotes        []*Quote               `protobuf:"bytes,1,rep,name=quotes,proto3" json:"quotes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealtimeQuotesReply) Reset() {
	*x = GetRealtimeQuotesReply{}
	mi := &file_market_v1_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealtimeQuotesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealtimeQuotesReply) ProtoMessage() {}

func (x *GetRealtimeQuotesReply) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealtimeQuotesReply.ProtoReflect.Descriptor instead.
func (*GetRealtimeQuotesReply) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{5}
}

func (x *GetRealtimeQuotesReply) GetQuotes() []*Quote {
	if x != nil {
		return x.Quotes
	}
	return nil
}

var File_market_v1_market_proto protoreflect.FileDescriptor

const file_market_v1_market_proto_rawDesc = "" +
	"\n" +
	"\x16market/v1/market.proto\x12\tmarket.v1\x1a\x1cgoogle/api/annotations.proto\"i\n" +
	"\n" +
	"StockBasic\x12\x17\n" +
	"\ats_code\x18\x01 \x01(\tR\x06tsCode\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06market\x18\x04 \x01(\tR\x06market\"E\n" +
	"\x13SearchStocksRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"B\n" +
	"\x11SearchStocksReply\x12-\n" +
	"\x06stocks\x18\x01 \x03(\v2\x15.market.v1.StockBasicR\x06stocks\"0\n" +
	"\x18GetRealtimeQuotesRequest\x12\x14\n" +
	"\x05codes\x18\x01 \x03(\tR\x05codes\"\xbe\x02\n" +
	"\x05Quote\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x12\x12\n" +
	"\x04open\x18\x04 \x01(\tR\x04open\x12\x1b\n" +
	"\tpre_close\x18\x05 \x01(\tR\bpreClose\x12\x12\n" +
	"\x04high\x18\x06 \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\a \x01(\tR\x03low\x12%\n" +
	"\x0echange_percent\x18\b \x01(\x01R\rchangePercent\x12!\n" +
	"\fchange_price\x18\t \x01(\x01R\vchangePrice\x12\x12\n" +
	"\x04date\x18\n" +
	" \x01(\tR\x04date\x12\x12\n" +
	"\x04time\x18\v \x01(\tR\x04time\x12\x16\n" +
	"\x06volume\x18\f \x01(\tR\x06volume\x12\x16\n" +
	"\x06amount\x18\r \x01(\tR\x06amount\"B\n" +
	"\x16GetRealtimeQuotesReply\x12(\n" +
	"\x06quotes\x18\x01 \x03(\v2\x10.market.v1.QuoteR\x06quotes2\x8c\x02\n" +
	"\rMarketService\x12r\n" +
	"\fSearchStocks\x12\x1e.market.v1.SearchStocksRequest\x1a\x1c.market.v1.SearchStocksReply\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/market/v1/stocks/search\x12\x86\x01\n" +
	"\x11GetRealtimeQuotes\x12#.market.v1.GetRealtimeQuotesRequest\x1a!.market.v1.GetRealtimeQuotesReply\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/market/v1/quotes/realtimeB\x1dZ\x1beino-stock/api/market/v1;v1b\x06proto3"

var (
	file_market_v1_market_proto_rawDescOnce sync.Once
	file_market_v1_market_proto_rawDescData []byte
)

func file_market_v1_market_proto_rawDescGZIP() []byte {
	file_market_v1_market_proto_rawDescOnce.Do(func() {
		file_market_v1_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_v1_market_proto_rawDesc), len(file_market_v1_market_proto_rawDesc)))
	})
	return file_market_v1_market_proto_rawDescData
}

var file_market_v1_market_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_market_v1_market_proto_goTypes = []any{
	(*StockBasic)(nil),               // 0: market.v1.StockBasic
	(*SearchStocksRequest)(nil),      // 1: market.v1.SearchStocksRequest
	(*SearchStocksReply)(nil),        // 2: market.v1.SearchStocksReply
	(*GetRealtimeQuotesRequest)(nil), // 3: market.v1.GetRealtimeQuotesRequest
	(*Quote)(nil),                    // 4: market.v1.Quote
	(*GetRealtimeQuotesReply)(nil),   // 5: market.v1.GetRealtimeQuotesReply
}
var file_market_v1_market_proto_depIdxs = []int32{
	0, // 0: market.v1.SearchStocksReply.stocks:type_name -> market.v1.StockBasic
	4, // 1: market.v1.GetRealtimeQuotesReply.quotes:type_name -> market.v1.Quote
	1, // 2: market.v1.MarketService.SearchStocks:input_type -> market.v1.SearchStocksRequest
	3, // 3: market.v1.MarketService.GetRealtimeQuotes:input_type -> market.v1.GetRealtimeQuotesRequest
	2, // 4: market.v1.MarketService.SearchStocks:output_type -> market.v1.SearchStocksReply
	5, // 5: market.v1.MarketService.GetRealtimeQuotes:output_type -> market.v1.GetRealtimeQuotesReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_market_v1_market_proto_init() }
func file_market_v1_market_proto_init() {
	if File_market_v1_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_v1_market_proto_rawDesc), len(file_market_v1_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_v1_market_proto_goTypes,
		DependencyIndexes: file_market_v1_market_proto_depIdxs,
		MessageInfos:      file_market_v1_market_proto_msgTypes,
	}.Build()
	File_market_v1_market_proto = out.File
	file_market_v1_market_proto_goTypes = nil
	file_market_v1_market_proto_depIdxs = nil
}
