// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.0
// source: market/v1/market.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMarketServiceGetRealtimeQuotes = "/market.v1.MarketService/GetRealtimeQuotes"
const OperationMarketServiceSearchStocks = "/market.v1.MarketService/SearchStocks"

type MarketServiceHTTPServer interface {
	GetRealtimeQuotes(context.Context, *GetRealtimeQuotesRequest) (*GetRealtimeQuotesReply, error)
	SearchStocks(context.Context, *SearchStocksRequest) (*SearchStocksReply, error)
}

func RegisterMarketServiceHTTPServer(s *http.Server, srv MarketServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/market/v1/stocks/search", _MarketService_SearchStocks0_HTTP_Handler(srv))
	r.POST("/api/market/v1/quotes/realtime", _MarketService_GetRealtimeQuotes0_HTTP_Handler(srv))
}

func _MarketService_SearchStocks0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchStocksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServiceSearchStocks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchStocks(ctx, req.(*SearchStocksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchStocksReply)
		return ctx.Result(200, reply)
	}
}

func _MarketService_GetRealtimeQuotes0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRealtimeQuotesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServiceGetRealtimeQuotes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRealtimeQuotes(ctx, req.(*GetRealtimeQuotesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRealtimeQuotesReply)
		return ctx.Result(200, reply)
	}
}

type MarketServiceHTTPClient interface {
	GetRealtimeQuotes(ctx context.Context, req *GetRealtimeQuotesRequest, opts ...http.CallOption) (rsp *GetRealtimeQuotesReply, err error)
	SearchStocks(ctx context.Context, req *SearchStocksRequest, opts ...http.CallOption) (rsp *SearchStocksReply, err error)
}

type MarketServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMarketServiceHTTPClient(client *http.Client) MarketServiceHTTPClient {
	return &MarketServiceHTTPClientImpl{client}
}

func (c *MarketServiceHTTPClientImpl) GetRealtimeQuotes(ctx context.Context, in *GetRealtimeQuotesRequest, opts ...http.CallOption) (*GetRealtimeQuotesReply, error) {
	var out GetRealtimeQuotesReply
	pattern := "/api/market/v1/quotes/realtime"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketServiceGetRealtimeQuotes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MarketServiceHTTPClientImpl) SearchStocks(ctx context.Context, in *SearchStocksRequest, opts ...http.CallOption) (*SearchStocksReply, error) {
	var out SearchStocksReply
	pattern := "/api/market/v1/stocks/search"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketServiceSearchStocks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
