// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"eino-stock/internal/biz/ai"
	"eino-stock/internal/biz/cron"
	"eino-stock/internal/biz/f10"
	"eino-stock/internal/biz/follow"
	"eino-stock/internal/biz/market"
	"eino-stock/internal/biz/prompt"
	"eino-stock/internal/biz/screen"
	"eino-stock/internal/conf"
	"eino-stock/internal/data"
	"eino-stock/internal/infrastructure"
	"eino-stock/internal/server"
	"eino-stock/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, dataSource *conf.DataSource, logger log.Logger) (*kratos.App, func(), error) {
	// Database
	db, err := data.NewDB("d:/go-stock/eino-stock/data/eino-stock.db")
	if err != nil {
		return nil, nil, err
	}

	// Market repo from eastmoney search
	searchClient := infrastructure.NewSearchClient(dataSource)

	// Quote / KLine clients
	quoteClient := infrastructure.NewQuoteClient(dataSource, logger)
	eastMoneyClient := infrastructure.NewEastMoneyKLineClient(dataSource, logger)
	sinaClient := infrastructure.NewSinaKLineClient(dataSource, logger)

	// Market usecase
	marketUsecase := market.NewMarketUsecase(searchClient, quoteClient, eastMoneyClient, sinaClient)
	marketService := service.NewMarketService(marketUsecase)

	// Screen
	screenClient := infrastructure.NewScreenClient(dataSource, logger)
	screenUsecase := screen.NewScreenUsecase(screenClient)
	screenService := service.NewScreenService(screenUsecase)

	// AI
	aiUsecase := ai.NewScreenUsecase()
	aiService := service.NewAIService(aiUsecase)

	// Follow (自选股)
	followRepo := data.NewFollowRepoImpl(db)
	followUsecase := follow.NewFollowUsecase(followRepo)
	followService := service.NewFollowService(followUsecase)

	// Settings
	settingsRepo := data.NewSettingRepo(db)
	settingsService := service.NewSettingsService(settingsRepo)

	// F10
	f10Client := infrastructure.NewF10Client(dataSource, logger)
	f10Usecase := f10.NewF10Usecase(f10Client)
	f10Service := service.NewF10Service(f10Usecase)

	// Cron
	cronTaskRepo := data.NewCronTaskRepo(db)
	cronScheduler := infrastructure.NewCronScheduler(logger)
	cronUsecase := cron.NewCronUsecase(cronTaskRepo, cronScheduler)
	cronService := service.NewCronService(cronUsecase)

	// Search
	promptRepo := data.NewPromptRepo(db)
	promptUsecase := prompt.NewPromptUsecase(promptRepo)
	promptService := service.NewPromptService(promptUsecase)

	searchService := service.NewSearchService()

	// Servers
	grpcServer := server.NewGRPCServer(confServer, logger)
	httpServer := server.NewHTTPServer(confServer, marketService, screenService, aiService, followService, settingsService, logger, f10Service, cronService, searchService, promptService)

	app := newApp(logger, grpcServer, httpServer)
	cleanup := func() {}
	return app, cleanup, nil
}
