export function GetConfig() { return fetch("/api/settings/get").then(r=>r.json()).catch(()=>({})) }
export function GetStockList(k) { return fetch("/api/market/stocks?keyword="+encodeURIComponent(k||"")+"&limit=50").then(r=>r.json()) }
export function Greet(c) { return fetch("/api/market/quote/"+encodeURIComponent(c)).then(r=>r.json()) }
export function GetStockKLine(c,n,d) { return fetch("/api/market/kline/"+encodeURIComponent(c)+"?ktype=101&limit="+(d||120)).then(r=>r.json()) }
export function GetStockEastMoneyKLine(c,n,k,d) { return GetStockKLine(c,n,d) }
export function GetStockKLineWithFallback(a,b,k,d) { return GetStockKLine(a,b,d) }
export function GetStockEastMoneyKLinePage(c,n,k,p,ps) { return GetStockKLine(c,n,p*(ps||400)) }
export function GetStockKLinePageWithFallback(c,n,k,p,ps) { return GetStockEastMoneyKLinePage(c,n,k,p,ps) }
export function GetStockCommonKLine(c,k,d) { return GetStockKLine(c,"",d) }
export function GetStockMinutePriceLineData(c) { return fetch("/api/tool/minute?code="+encodeURIComponent(c)).then(r=>r.json()) }
export function GetStockRealTimePrice(c) { return Greet(c) }
export function GetStockMoneyTrendByDay(c,d) { return fetch("/api/tool/detail?code="+encodeURIComponent(c)).then(r=>r.json()) }
export function GetFollowList(g) { return fetch("/api/follow/list").then(r=>r.json()) }
export function Follow(c) { return fetch("/api/follow/add?code="+c+"&name=",{method:"POST"}).then(r=>r.json()) }
export function UnFollow(c) { return fetch("/api/follow/remove?code="+c,{method:"POST"}).then(r=>r.json()) }
export function NewChatStream(s,c,q) { return fetch("/api/ai/chat?q="+encodeURIComponent(q||c)).then(async r=>{let o="";const h=await r.body.getReader(),d=new TextDecoder;while(true){const{done,value}=await h.read();if(done)return o;const ls=d.decode(value,{stream:!0}).split("\n");for(const l of ls){if(!l.startsWith("data: "))continue;try{const e=JSON.parse(l.slice(6));if(e.type==="text")o+=e.content}catch{}}}}) }
export function ChatWithAgent(s,c,q,sp,ai,t,a) { return NewChatStream(s,c,q) }
export function AbortChatWithAgent() { return Promise.resolve() }
export function AbortSummaryStockNews() { return Promise.resolve() }
export function GlobalStockIndexes() { return fetch("/api/market/global-indexes").then(r=>r.json()) }
export function GetHotStrategy() { return fetch("/api/screen/hot-strategy").then(r=>r.json()) }
export function GetIndustryRank(s,c) { return fetch("/api/tool/industry-valuation?bkName=").then(r=>r.json()) }
export function GetTelegraphList(s) { return fetch("/api/market/telegraph-list?keyword="+encodeURIComponent(s||"")).then(r=>r.json()) }
export function ReFleshTelegraphList(s) { return GetTelegraphList(s) }
export function GetAiConfigs() { return Promise.resolve([{ID:1,Name:"default"}]) }
export function GetPromptTemplates(t,k) { return fetch('/api/prompt/list').then(r=>r.json()) }
export function GetPromptTemplateList(q) { return fetch('/api/prompt/list').then(r=>r.json()) }
export function AddPromptTemplate(t) { return fetch('/api/prompt/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(t)}).then(r=>r.json()) }
export function UpdatePromptTemplate(t) { return fetch('/api/prompt/update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(t)}).then(r=>r.json()) }
export function DeletePromptTemplate(id) { return fetch('/api/prompt/delete?id='+id,{method:'POST'}).then(r=>r.json()) }
export function AddPrompt(tag) { return Promise.resolve("ok") }
export function DelPrompt(tag) { return Promise.resolve("ok") }
export function IsTradingTime() { return Promise.resolve(true) }
export function IsHKTradingTime() { return Promise.resolve(true) }
export function IsUSTradingTime() { return Promise.resolve(true) }
export function IsTradingDay(d) { return Promise.resolve(true) }
export function GetLatestTradingDay() { return Promise.resolve(new Date().toISOString().slice(0,10)) }
export function GetVersionInfo() { return Promise.resolve({Version:"1.0.0",OfficialStatement:"eino-stock"}) }
export function GetGroupList() { return Promise.resolve([]) }
export function AddGroup(n) { return Promise.resolve("ok") }
export function RemoveGroup(id) { return Promise.resolve("ok") }
export function InitializeGroupSort() { return Promise.resolve(true) }
export function AddStockGroup(g,c) { return Promise.resolve("ok") }
export function RemoveStockGroup(g,c,n) { return Promise.resolve("ok") }
export function UpdateGroupSort(g,s) { return Promise.resolve("ok") }
export function GetGroupStockList(g) { return fetch("/api/follow/list").then(r=>r.json()) }
export function GetChipDistribution(c,n,b,d) { return Promise.resolve({items:[],avgCost:0,profitRatio:0}) }
export function GetStockChanges(t,p,s) { return Promise.resolve({Data:[],Total:0}) }
export function GetAllStockChangesWithPaging(q) { return Promise.resolve({data:[],total:0}) }
export function GetChangeRank(s,c) { return Promise.resolve([]) }
export function GetChangeTypeDailyStats(d) { return Promise.resolve([]) }
export function GetDailyChangeStats(d) { return Promise.resolve([]) }
export function GetDailyDimensionStats(d,di,s) { return Promise.resolve([]) }
export function GetTypeStatsByDate(d) { return Promise.resolve([]) }
export function GetStockChangeHistory(q) { return Promise.resolve({data:[],total:0}) }
export function SaveStockChangesToHistory(c) { return Promise.resolve(0) }
export function DeleteStockChangeHistory(id) { return Promise.resolve("ok") }
export function StockNotice(c) { return fetch("/api/tool/notice?code="+encodeURIComponent(c)).then(r=>r.json()) }
export function StockResearchReport(c) { return fetch("/api/tool/report?code="+encodeURIComponent(c)+"&days=30").then(r=>r.json()) }
export function SummaryStockNews(c,n,s,a,t,p) { return Promise.resolve({Content:"AI鏆備笉鍙敤"}) }
export function SaveAIResponseResult(c,n,co,s,p) { return Promise.resolve() }
export function GetAIResponseResult(t) { return Promise.resolve([]) }
export function GetAIResponseResultList(q) { return Promise.resolve({data:[],total:0}) }
export function BatchDeleteAIResponseResult(ids) { return Promise.resolve() }
export function DeleteAIResponseResult(id) { return Promise.resolve() }
export function FetchAiModels(p,k) { return Promise.resolve([]) }
export function FetchAiModelInfo(p,k,m) { return Promise.resolve({}) }
export function SaveAiAssistantSession(s,m) { return Promise.resolve() }
export function GetAiAssistantSession(s) { return Promise.resolve(null) }
export function GetAllCustomStrategies() { return Promise.resolve([]) }
export function GetCustomStrategyList(q) { return Promise.resolve({data:[],total:0}) }
export function SaveCustomStrategy(s) { return Promise.resolve("ok") }
export function DeleteCustomStrategy(id) { return Promise.resolve("ok") }
export function GetAllStocks(k,p,s,m) { return fetch("/api/market/stocks?keyword="+encodeURIComponent(k||"")+"&limit="+(s||50)).then(r=>r.json()) }
export function GetAllStockInfoList(q) { return Promise.resolve({data:[],total:0}) }
export function GetAllStockInfoById(id) { return Promise.resolve(null) }
export function AddAllStockInfo(i) { return Promise.resolve("ok") }
export function DeleteAllStockInfo(id) { return Promise.resolve("ok") }
export function BatchDeleteAllStockInfo(ids) { return Promise.resolve("ok") }
export function GetAllConcepts() { return Promise.resolve([]) }
export function GetAllIndustries() { return Promise.resolve([]) }
export function GetAllMarkets() { return Promise.resolve([]) }
export function GetfundList(k) { return Promise.resolve([]) }
export function GetFundRanking(t,p,pg,ps,s,o) { return Promise.resolve([]) }
export function GetFundKLine(c,k,d) { return Promise.resolve([]) }
export function GetFundHistoryNetValue(c,sd,ed,d) { return Promise.resolve([]) }
export function GetFundTop10Holdings(c) { return Promise.resolve([]) }
export function GetFollowedFund() { return Promise.resolve([]) }
export function GetFollowedFundPaged(p,ps,k) { return Promise.resolve({data:[],total:0}) }
export function FollowFund(c) { return Promise.resolve("ok") }
export function UnFollowFund(c) { return Promise.resolve("ok") }
export function GetIndustryMoneyRankSina(s,c) { return fetch("/api/tool/industry-money-rank").then(r=>r.json()) }
export function GetMoneyRankSina(s) { return Promise.resolve([]) }
export function GetUplimitHot(p,ps) { return fetch("/api/tool/hot-plates").then(r=>r.json()) }
export function LongTigerRank(c) { return fetch("/api/tool/long-tiger").then(r=>r.json()) }
export function ClsCalendar() { return Promise.resolve([]) }
export function InvestCalendarTimeLine(y) { return Promise.resolve([]) }
export function NewsPush(s) { return Promise.resolve([]) }
export function HotEvent(d) { return Promise.resolve([]) }
export function HotStock(d) { return Promise.resolve([]) }
export function HotTopic(d) { return Promise.resolve([]) }
export function IndustryResearchReport(k) { return Promise.resolve([]) }
export function AnalyzeSentiment(t) { return Promise.resolve({}) }
export function AnalyzeSentimentWithFreqWeight(t) { return Promise.resolve({}) }
export function SendDingDingMessage(m,u) { return Promise.resolve("ok") }
export function SendDingDingMessageByType(m,t,u) { return Promise.resolve("ok") }
export function SetAlarmChangePercent(c,p,e) { return Promise.resolve("ok") }
export function SetCostPriceAndVolume(c,p,v) { return Promise.resolve("ok") }
export function SetStockSort(c,s) { return Promise.resolve("ok") }
export function SetTradingPrice(c,e,tp,sl,cp) { return Promise.resolve("璁剧疆鎴愬姛") }
export function SetStockAICron(c,e) { return Promise.resolve("ok") }
export function GetTradingRecordList(q) { return Promise.resolve({data:[],total:0}) }
export function GetTradingRecordById(id) { return Promise.resolve(null) }
export function GetTradingRecordStatistics() { return Promise.resolve({}) }
export function AddTradingRecord(r) { return Promise.resolve("ok") }
export function UpdateTradingRecord(r) { return Promise.resolve("ok") }
export function DeleteTradingRecord(id) { return Promise.resolve("ok") }
export function InitCronTasks() { return Promise.resolve() }
export function GetCronTaskList(q) { return Promise.resolve({data:[],total:0}) }
export function GetCronTaskByID(id) { return Promise.resolve(null) }
export function CreateCronTask(t) { return Promise.resolve("鍒涘缓鎴愬姛") }
export function UpdateCronTask(t) { return Promise.resolve("鏇存柊鎴愬姛") }
export function DeleteCronTask(id) { return Promise.resolve("ok") }
export function EnableCronTask(id,e) { return Promise.resolve("ok") }
export function ExecuteCronTaskNow(id) { return Promise.resolve("ok") }
export function GetCronTaskTypes() { return Promise.resolve([]) }
export function SearchCronTasks(k) { return Promise.resolve([]) }
export function ValidateCronExpr(e) { return Promise.resolve(null) }
export function CalculateNextRunTime(e) { return Promise.resolve(new Date().toISOString()) }
export function CalculateNextRunTimes(e,c) { return Promise.resolve([]) }
export function GetMCPServerList(q) { return Promise.resolve({data:[],total:0}) }
export function GetMCPServerByID(id) { return Promise.resolve(null) }
export function CreateMCPServer(s) { return Promise.resolve("鍒涘缓鎴愬姛") }
export function UpdateMCPServer(s) { return Promise.resolve("鏇存柊鎴愬姛") }
export function DeleteMCPServer(id) { return Promise.resolve("ok") }
export function EnableMCPServer(id,e) { return Promise.resolve("ok") }
export function TestMCPServer(id) { return Promise.resolve("ok") }
export function GetAllMCPTools() { return Promise.resolve([]) }
export function GetMCPToolsByServerID(id) { return Promise.resolve([]) }
export function GetAllSkills() { return Promise.resolve([]) }
export function GetSkillList(q) { return Promise.resolve({data:[],total:0}) }
export function GetSkillByID(id) { return Promise.resolve(null) }
export function CreateSkill(s) { return Promise.resolve("鍒涘缓鎴愬姛") }
export function UpdateSkill(s) { return Promise.resolve("鏇存柊鎴愬姛") }
export function DeleteSkill(id) { return Promise.resolve("ok") }
export function EnableSkill(id,e) { return Promise.resolve("ok") }
export function GetAiRecommendStocksList(q) { return Promise.resolve({data:[],total:0}) }
export function DeleteAiRecommendStocks(id) { return Promise.resolve() }
export function UpdateAiRecommendStocksAlert(id,a) { return Promise.resolve() }
export function SaveAsMarkdown(c,f) { return Promise.resolve("ok") }
export function SaveImage(b,f) { return Promise.resolve("ok") }
export function SaveWordFile(c,f) { return Promise.resolve("ok") }
export function ShareAnalysis(c,f) { return Promise.resolve("ok") }
export function ShareText(t,title) { return Promise.resolve("ok") }
export function GetUserManual() { return Promise.resolve({Content:""}) }
export function GetTimezone() { return Promise.resolve(Intl.DateTimeFormat().resolvedOptions().timeZone) }
export function GetTodayMarketStatistic() { return Promise.resolve({}) }
export function GetMarketStatisticByDate(d) { return Promise.resolve({}) }
export function GetRecentDaysMarketStatistic(d) { return Promise.resolve([]) }
export function FetchAndSaveMarketStatistic() { return Promise.resolve("ok") }
export function CheckFrequentTrading(c) { return Promise.resolve("") }
export function CheckStockBaseInfo(c) { return Promise.resolve(null) }
export function CheckDeviceBinding(d,k) { return Promise.resolve(true) }
export function HideToTray() { return Promise.resolve() }
export function ShowFromTray() { return Promise.resolve() }
export function QuitApp() { window.close(); return Promise.resolve() }
export function RestartAsAdmin() { return Promise.resolve("ok") }
export function ExportConfig() { return fetch("/api/settings/get").then(r=>r.json()) }
export function GetMachineId() { return Promise.resolve("web-"+Math.random().toString(36).slice(2,10)) }
export function CheckUpdate(v) { return Promise.resolve({HasUpdate:false,Version:"1.0.0"}) }
export function GetEffectiveSponsorVip() { return Promise.resolve({}) }
export function GetSponsorInfo() { return Promise.resolve({}) }
export function CheckSponsorCode(c) { return Promise.resolve(false) }
export function SearchStock(c) { return fetch("/api/market/stocks?keyword="+encodeURIComponent(c)+"&limit=10").then(r=>r.json()) }
export function TdxCallAuction() { return Promise.resolve([]) }
export function GetTdxCompanyCategoryList() { return Promise.resolve([]) }
export function GetTdxCompanyCategoryContent() { return Promise.resolve("") }
export function GetTdxCompanyInfo() { return Promise.resolve({}) }
export function GetTdxFinanceInfo() { return Promise.resolve({}) }
export function GetTdxXDXRInfo() { return Promise.resolve([]) }
export function UpdateConfig(cfg) { return Promise.resolve("ok") }

export function EMDictCode(code) { return Promise.resolve(code); }
export function OpenURL(u) { window.open(u,'_blank') }





export function GetBKFundFlowListByDate(t) { return Promise.resolve([]) }
export function GetBKFundFlowTopListByDate(t,e,n) { return Promise.resolve([]) }
export function GetAllBKCodes() { return Promise.resolve([]) }
